# Generated by Django 5.2 on 2025-05-04 10:07

import django.core.validators
import django.utils.timezone
import home_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', home_app.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('year', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2023), django.core.validators.MaxValueValidator(2080)])),
            ],
            options={
                'db_table': 'years',
            },
        ),
    ]
