# Generated by Django 5.2 on 2025-05-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='family_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
